# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x08grpc_api\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x0fTimeZoneRequest\x12\x10\n\x08timezone\x18\x01 \x01(\t\"\"\n\x0f\x44\x61yTimeResponse\x12\x0f\n\x07\x64\x61ytime\x18\x01 \x01(\t\"\x12\n\x10TimestampRequest\"B\n\x11TimestampResponse\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x15\n\x05Value\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\rPreviousValue\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xea\x01\n\x07\x44\x61yTime\x12?\n\x07\x64\x61ytime\x12\x19.grpc_api.TimeZoneRequest\x1a\x19.grpc_api.DayTimeResponse\x12\x44\n\ttimestamp\x12\x1a.grpc_api.TimestampRequest\x1a\x1b.grpc_api.TimestampResponse\x12/\n\x03set\x12\x0f.grpc_api.Value\x1a\x17.grpc_api.PreviousValue\x12\'\n\x03get\x12\x0f.grpc_api.Empty\x1a\x0f.grpc_api.Valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEZONEREQUEST']._serialized_start=56
  _globals['_TIMEZONEREQUEST']._serialized_end=91
  _globals['_DAYTIMERESPONSE']._serialized_start=93
  _globals['_DAYTIMERESPONSE']._serialized_end=127
  _globals['_TIMESTAMPREQUEST']._serialized_start=129
  _globals['_TIMESTAMPREQUEST']._serialized_end=147
  _globals['_TIMESTAMPRESPONSE']._serialized_start=149
  _globals['_TIMESTAMPRESPONSE']._serialized_end=215
  _globals['_VALUE']._serialized_start=217
  _globals['_VALUE']._serialized_end=238
  _globals['_PREVIOUSVALUE']._serialized_start=240
  _globals['_PREVIOUSVALUE']._serialized_end=269
  _globals['_EMPTY']._serialized_start=271
  _globals['_EMPTY']._serialized_end=278
  _globals['_DAYTIME']._serialized_start=281
  _globals['_DAYTIME']._serialized_end=515
# @@protoc_insertion_point(module_scope)
