# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DayTimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.daytime = channel.unary_unary(
                '/grpc_api.DayTime/daytime',
                request_serializer=api__pb2.TimeZoneRequest.SerializeToString,
                response_deserializer=api__pb2.DayTimeResponse.FromString,
                _registered_method=True)
        self.timestamp = channel.unary_unary(
                '/grpc_api.DayTime/timestamp',
                request_serializer=api__pb2.TimestampRequest.SerializeToString,
                response_deserializer=api__pb2.TimestampResponse.FromString,
                _registered_method=True)
        self.set = channel.unary_unary(
                '/grpc_api.DayTime/set',
                request_serializer=api__pb2.Value.SerializeToString,
                response_deserializer=api__pb2.PreviousValue.FromString,
                _registered_method=True)
        self.get = channel.unary_unary(
                '/grpc_api.DayTime/get',
                request_serializer=api__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.Value.FromString,
                _registered_method=True)


class DayTimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def daytime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def timestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DayTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'daytime': grpc.unary_unary_rpc_method_handler(
                    servicer.daytime,
                    request_deserializer=api__pb2.TimeZoneRequest.FromString,
                    response_serializer=api__pb2.DayTimeResponse.SerializeToString,
            ),
            'timestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.timestamp,
                    request_deserializer=api__pb2.TimestampRequest.FromString,
                    response_serializer=api__pb2.TimestampResponse.SerializeToString,
            ),
            'set': grpc.unary_unary_rpc_method_handler(
                    servicer.set,
                    request_deserializer=api__pb2.Value.FromString,
                    response_serializer=api__pb2.PreviousValue.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=api__pb2.Empty.FromString,
                    response_serializer=api__pb2.Value.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_api.DayTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_api.DayTime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DayTime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def daytime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_api.DayTime/daytime',
            api__pb2.TimeZoneRequest.SerializeToString,
            api__pb2.DayTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def timestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_api.DayTime/timestamp',
            api__pb2.TimestampRequest.SerializeToString,
            api__pb2.TimestampResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_api.DayTime/set',
            api__pb2.Value.SerializeToString,
            api__pb2.PreviousValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_api.DayTime/get',
            api__pb2.Empty.SerializeToString,
            api__pb2.Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
