version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "50051:50051"  # gRPCの標準ポートを使用
    volumes:
      - data-volume:/data  # データ永続化が必要な場合に使用
    depends_on:
      - init

  client:
    build:
      context: ./client
    depends_on:
      - server

  init:
    image: ubuntu:jammy
    volumes:
      - data-volume:/data
    command: /bin/sh -c "chown -R 1000:1000 /data"

volumes:
  data-volume:
