version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    env_file:
      - ../.env

  client:
    build:
      context: ./client
    depends_on:
      - server
    env_file:
      - ../.env

volumes:
  data-volume:
